In [ ]:
Exercises

### Exercise

A. Create an ndarry object (A) with any values from 1 to 100 in a nested Python List. You can choose your range from the given values (1-100).

* Given that A is an ndarray object, many functionalities in numpy could be accessed by:
    + Make sure to explain each line of codes that you have created.

1. Using a property of the ndarray object
      - e.g. `A.shape`
2. Using a method of the ndarray object
      - e.g. `A.max()`
3. Using a numpy function and passing an ndarray
     - e.g. `np.max(A)`

B. Create a 5x5 integer-array filled with ones.
* Check its shape, size, and number of dimensions. Explain briefly the codes you have created by writing a comment beside the code.

C. Create an array of values from -5 to + 5. Multiply each value with 2. Print the resulting array.

In [ ]:
import numpy as np
# A. Create an ndarray object (A) with values from 1 to 100 in a nested Python List.
A = np.array([[i for i in range(1, 101)]])  # Creates a 1x100 ndarray with values from 1 to 100

# Property of the ndarray object: Shape of the array
print("\nShape of A:", A.shape)  # Prints the shape of A

# Method of the ndarray object: Maximum value in the array
print("\nMaximum value in A:", A.max())  # Prints the maximum value in A

# Numpy function: Maximum value in the array
print("\nMaximum value in A (using np.max):", np.max(A))  # Prints the maximum value in A using np.max()

# B. Create a 5x5 integer-array filled with ones.
ones_array = np.ones((5, 5), dtype=int)  # a 5x5 array filled with ones


print("\nShape of ones_array:", ones_array.shape)  # Prints the shape of ones_array
print("\nSize of ones_array:", ones_array.size)    # Prints the size of ones_array
print("\nNumber of dimensions of ones_array:", ones_array.ndim)  # Prints the number of dimensions of ones_array

# C. Create an array of values from -5 to +5. Multiply each value by 2.
values = np.arange(-5, 6)  # Creates an array of values from -5 to +5
result_array = values * 2  # Multiplies each value in the array by 2

# Prints the resulting array
print("\nResulting array after multiplying each value by 2:", result_array)


Shape of A: (1, 100)
Maximum value in A: 100
Maximum value in A (using np.max): 100
Shape of ones_array: (5, 5)
Size of ones_array: 25
Number of dimensions of ones_array: 2
Resulting array after multiplying each value by 2: [-10  -8  -6  -4  -2   0   2   4   6   8  10]


### Exercise

A. Choose the values from the range of numbers 1 to 100.
1. Create an array with 30 values within the range of numbers given. You can choose your own start value and stop value. However, the incrementing value will be 2.
   * Explain what is the result briefly by writing a comment before the code.
2. Multiply the resulting array with 3. Print the result.

In [ ]:
# Array with 30 values within the range of 1 to 100, with an increment of 2
# The result is an array that contains 30 integer values starting from 3 and ending at 177, and it was spaced by 6.
import numpy as np

array = np.arange(1, 60, 2)

#Multiplying the array by 3
result = array * 3

print(result)


[  3   9  15  21  27  33  39  45  51  57  63  69  75  81  87  93  99 105
 111 117 123 129 135 141 147 153 159 165 171 177]


### Exercise

A. Create a four-dimensional array of random integers in the interval [0, 12]. Print the result.
1. Get the dimensions, shape, and size.
    * Explain what is the result briefly by writing a comment before the code.

B. Get the maximum number for each dimensions and display it.
   * Explain what is the result briefly by writing a comment before the code.

C. Multipy each array with 4. What is its result?
    * Write a brief explanation on the multiplication process.


In [ ]:
#In this result four-dimensional array of random integer is displayed chosen from the interval [0, 12]
four_dimAr = np.random.randint(0, 13, size=(3, 4, 5, 6))
print("Four-dimensional array:")
print(four_dimAr )


#The output for "Array Dimensions:" displays the number of dimensions of the array, which is 4.

print("\nArray Dimensions:")
print(four_dimAr.ndim)

#The output for "Array Shape:" displays the shape of the array. The shape is (3, 4, 5, 6), which means the array has:
# 3 elements along the first axis,
# 4 elements along the second axis,
# 5 elements along the third axis,
# 6 elements along the fourth axis.
print("\nArray Shape:")
print(four_dimAr .shape)

# The output for "Array Size:" displays the total number of elements in the array, which is 360 (3 * 4 * 5 * 6).
print("\nArray Size:")
print( four_dimAr .size)

#The result displays maximum number for each dimensions.
print("\nMaximum number for each dimension:")
max_perDim = [np.max(four_dimAr [:, :, :, i]) for i in range(four_dimAr .shape[3])]
print(max_perDim )


# the result dispalys the multiplied four-dimensional array by 4 and stores the result in a new array called multiplied_array.
multiplied_array = four_dimAr  * 4
print("\n\nMultiplied array by 4:")
print(multiplied_array)

Four-dimensional array:
[[[[ 7  2  7 12 11  8]
   [ 1  1  3 11  4  6]
   [ 6 11  5  3  4  8]
   [ 9  1 11  8  5  4]
   [ 8  3  1  3  2 12]]

  [[10 12  7  0  4  3]
   [12  8  7 12  3 12]
   [ 3 10  8  5  2  0]
   [ 5  8 11 12  1  3]
   [12 12 11  8 10  0]]

  [[ 2  9  9  9  8  4]
   [ 2  6 12  7  0 11]
   [ 8 10  9  3 12  8]
   [ 2  4 12 11  0  9]
   [ 6 11 11  7  5 11]]

  [[12  8  0  4  6  2]
   [10  4  0  6  1  2]
   [ 5  3  0  4  4 12]
   [ 1  4  0  2  7 11]
   [ 3  3  0 12 12  0]]]


 [[[ 4  4  6  1  0 10]
   [ 4  5  4  9  0  2]
   [ 5  9  6  0  9  5]
   [10 10  9  7  6  7]
   [12  1  0  4  4  6]]

  [[10 12  8  3  9  9]
   [12 12 12 11  0  1]
   [12 11  9 12 12 12]
   [ 1  1  6  6  3  1]
   [ 3  0 12  7  7  2]]

  [[12  6  6  4  0  8]
   [ 6  0 12  1  7  7]
   [ 8  0  7  9  5  6]
   [ 1  1  3  6  6  1]
   [ 1 12  9  1  5  7]]

  [[ 5 12  3  9  1  6]
   [ 0  5 10 10  9  3]
   [ 0 10  3 10  7  1]
   [12  8  0  7 12  3]
   [ 2 10  3  7 11  2]]]


 [[[11  3  3  3  2  0]
   [ 6  4  5 